/*
|-----------------------------------------
| setting up AllIcons for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, April, 2026
|-----------------------------------------
*/

import {
  ShieldCheck,
  FolderKanban,
  FileSignature,
  User,
  Users,
  FileText,
  Settings,
  Info,
  Wrench,
  Phone,
  HelpCircle,
  Menu,
  Lock,
  ScrollText,
  FileBadge,
  Eye,
  Edit2,
  Trash2,
  Plus,
  GripVertical,
  Save,
  ChevronDown,
  ChevronRight,
  Home,
  Search,
  Bell,
  Mail,
  Calendar,
  Clock,
  Download,
  Upload,
  Copy,
  Check,
  X,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Filter,
  RefreshCw,
  ExternalLink,
  Link,
  Unlink,
  ImageIcon,
  Video,
  Music,
  Camera,
  Mic,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FileX,
  Bookmark,
  BookmarkPlus,
  Star,
  Heart,
  Share2,
  MessageSquare,
  MessageCircle,
  Send,
  Paperclip,
  Tag,
  Hash,
  AtSign,
  Globe,
  MapPin,
  Navigation,
  Target,
  Award,
  Zap,
  Sun,
  Moon,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Power,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
} from 'lucide-react';
import { AiOutlineBell } from 'react-icons/ai';
import { BsBoxArrowRight, BsBoxes, BsFillPersonLinesFill, BsGrid3X3Gap } from 'react-icons/bs';
import { CiBoxList, CiCircleInfo, CiFacebook, CiGrid2V, CiGrid32, CiInboxIn, CiInstagram, CiShop, CiViewTimeline } from 'react-icons/ci';
import { FaCrown, FaFacebook, FaFacebookMessenger, FaInfoCircle, FaInstagramSquare, FaWhatsapp } from 'react-icons/fa';
import { FaBoxArchive } from 'react-icons/fa6';
import { FiGrid } from 'react-icons/fi';
import { GiJewelCrown } from 'react-icons/gi';
import { IoIosCheckmarkCircleOutline, IoIosCloseCircleOutline, IoMdCheckmarkCircleOutline } from 'react-icons/io';
import { IoAirplaneOutline, IoBarChartOutline, IoCalendarOutline, IoLogoDropbox, IoLogoWhatsapp } from 'react-icons/io5';
import { LuCrown } from 'react-icons/lu';
import { MdMarkEmailUnread, MdOutlineEmail } from 'react-icons/md';
import { SiSendgrid } from 'react-icons/si';
import { TfiLayoutGrid4Alt } from 'react-icons/tfi';

export const iconMap: Record<string, React.ReactNode> = {
  ShieldCheck: <ShieldCheck size={18} />,
  FolderKanban: <FolderKanban size={16} />,
  FileSignature: <FileSignature size={16} />,
  User: <User size={16} />,
  Users: <Users size={16} />,
  FileText: <FileText size={16} />,
  Settings: <Settings size={18} />,
  Info: <Info size={16} />,
  Wrench: <Wrench size={16} />,
  Phone: <Phone size={16} />,
  HelpCircle: <HelpCircle size={16} />,
  Menu: <Menu size={16} />,
  Lock: <Lock size={16} />,
  ScrollText: <ScrollText size={16} />,
  FileBadge: <FileBadge size={16} />,
  Eye: <Eye size={16} />,
  Edit2: <Edit2 size={16} />,
  Trash2: <Trash2 size={16} />,
  Plus: <Plus size={16} />,
  GripVertical: <GripVertical size={16} />,
  Save: <Save size={16} />,
  ChevronDown: <ChevronDown size={16} />,
  ChevronRight: <ChevronRight size={16} />,
  Home: <Home size={16} />,
  Search: <Search size={16} />,
  Bell: <Bell size={16} />,
  Mail: <Mail size={16} />,
  Calendar: <Calendar size={16} />,
  Clock: <Clock size={16} />,
  Download: <Download size={16} />,
  Upload: <Upload size={16} />,
  Copy: <Copy size={16} />,
  Check: <Check size={16} />,
  X: <X size={16} />,
  AlertCircle: <AlertCircle size={16} />,
  AlertTriangle: <AlertTriangle size={16} />,
  ArrowLeft: <ArrowLeft size={16} />,
  ArrowRight: <ArrowRight size={16} />,
  ArrowUp: <ArrowUp size={16} />,
  ArrowDown: <ArrowDown size={16} />,
  Filter: <Filter size={16} />,
  RefreshCw: <RefreshCw size={16} />,
  ExternalLink: <ExternalLink size={16} />,
  Link: <Link size={16} />,
  Unlink: <Unlink size={16} />,
  Image: <ImageIcon size={16} />,
  Video: <Video size={16} />,
  Music: <Music size={16} />,
  Camera: <Camera size={16} />,
  Mic: <Mic size={16} />,
  ShoppingCart: <ShoppingCart size={16} />,
  CreditCard: <CreditCard size={16} />,
  DollarSign: <DollarSign size={16} />,
  Package: <Package size={16} />,
  BarChart: <BarChart size={16} />,
  PieChart: <PieChart size={16} />,
  TrendingUp: <TrendingUp size={16} />,
  TrendingDown: <TrendingDown size={16} />,
  Activity: <Activity size={16} />,
  Database: <Database size={16} />,
  Server: <Server size={16} />,
  Cloud: <Cloud size={16} />,
  CloudUpload: <CloudUpload size={16} />,
  CloudDownload: <CloudDownload size={16} />,
  Folder: <Folder size={16} />,
  FolderOpen: <FolderOpen size={16} />,
  File: <File size={16} />,
  FilePlus: <FilePlus size={16} />,
  FileX: <FileX size={16} />,
  Bookmark: <Bookmark size={16} />,
  BookmarkPlus: <BookmarkPlus size={16} />,
  Star: <Star size={16} />,
  Heart: <Heart size={16} />,
  Share2: <Share2 size={16} />,
  MessageSquare: <MessageSquare size={16} />,
  MessageCircle: <MessageCircle size={16} />,
  Send: <Send size={16} />,
  Paperclip: <Paperclip size={16} />,
  Tag: <Tag size={16} />,
  Hash: <Hash size={16} />,
  AtSign: <AtSign size={16} />,
  Globe: <Globe size={16} />,
  MapPin: <MapPin size={16} />,
  Navigation: <Navigation size={16} />,
  Target: <Target size={16} />,
  Award: <Award size={16} />,
  Zap: <Zap size={16} />,
  Sun: <Sun size={16} />,
  Moon: <Moon size={16} />,
  Volume2: <Volume2 size={16} />,
  VolumeX: <VolumeX size={16} />,
  Play: <Play size={16} />,
  Pause: <Pause size={16} />,
  SkipBack: <SkipBack size={16} />,
  SkipForward: <SkipForward size={16} />,
  Power: <Power size={16} />,
  LogIn: <LogIn size={16} />,
  LogOut: <LogOut size={16} />,
  UserPlus: <UserPlus size={16} />,
  UserMinus: <UserMinus size={16} />,
  UserCheck: <UserCheck size={16} />,
  CiShop: <CiShop size={16} />,
  CiFacebook: <CiFacebook size={16} />,
  FaFacebook: <FaFacebook size={16} />,
  FaWhatsapp: <FaWhatsapp size={16} />,
  IoLogoWhatsapp: <IoLogoWhatsapp size={16} />,
  CiInstagram: <CiInstagram size={16} />,
  FaInstagramSquare: <FaInstagramSquare size={16} />,
  FaFacebookMessenger: <FaFacebookMessenger size={16} />,
  MdOutlineEmail: <MdOutlineEmail size={16} />,
  MdMarkEmailUnread: <MdMarkEmailUnread size={16} />,
  FaCrown: <FaCrown size={16} />,
  LuCrown: <LuCrown size={16} />,
  GiJewelCrown: <GiJewelCrown size={16} />,
  FaInfoCircle: <FaInfoCircle size={16} />,
  CiCircleInfo: <CiCircleInfo size={16} />,
  CiBoxList: <CiBoxList size={16} />,
  CiInboxIn: <CiInboxIn size={16} />,
  IoLogoDropbox: <IoLogoDropbox size={16} />,
  FaBoxArchive: <FaBoxArchive size={16} />,
  BsBoxArrowRight: <BsBoxArrowRight size={16} />,
  BsBoxes: <BsBoxes size={16} />,
  CiGrid32: <CiGrid32 size={16} />,
  CiGrid2V: <CiGrid2V size={16} />,
  FiGrid: <FiGrid size={16} />,
  BsGrid3X3Gap: <BsGrid3X3Gap size={16} />,
  SiSendgrid: <SiSendgrid size={16} />,
  TfiLayoutGrid4Alt: <TfiLayoutGrid4Alt size={16} />,
  IoMdCheckmarkCircleOutline: <IoMdCheckmarkCircleOutline size={16} />,
  IoAirplaneOutline: <IoAirplaneOutline size={16} />,
  IoBarChartOutline: <IoBarChartOutline size={16} />,
  IoCalendarOutline: <IoCalendarOutline size={16} />,
  CiViewTimeline: <CiViewTimeline size={16} />,
  IoIosCheckmarkCircleOutline: <IoIosCheckmarkCircleOutline size={16} />,
  IoIosCloseCircleOutline: <IoIosCloseCircleOutline size={16} />,
  AiOutlineBell: <AiOutlineBell size={16} />,
  BsFillPersonLinesFill: <BsFillPersonLinesFill size={16} />,
};

export const iconOptions = Object.keys(iconMap);
