/*
|-----------------------------------------
| setting up AllIconsJsx for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, April, 2026
|-----------------------------------------
*/

import type { ComponentType, SVGProps } from 'react';
import {
  ShieldCheck,
  FolderKanban,
  FileSignature,
  User,
  Users,
  FileText,
  Settings,
  Info,
  Wrench,
  Phone,
  HelpCircle,
  Menu,
  Lock,
  ScrollText,
  FileBadge,
  Eye,
  Edit2,
  Trash2,
  Plus,
  GripVertical,
  Save,
  ChevronDown,
  ChevronRight,
  Home,
  Search,
  Bell,
  Mail,
  Calendar,
  Clock,
  Download,
  Upload,
  Copy,
  Check,
  X,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Filter,
  RefreshCw,
  ExternalLink,
  Link,
  Unlink,
  ImageIcon,
  Video,
  Music,
  Camera,
  Mic,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FileX,
  Bookmark,
  BookmarkPlus,
  Star,
  Heart,
  Share2,
  MessageSquare,
  MessageCircle,
  Send,
  Paperclip,
  Tag,
  Hash,
  AtSign,
  Globe,
  MapPin,
  Navigation,
  Target,
  Award,
  Zap,
  Sun,
  Moon,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Power,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
} from 'lucide-react';
import { AiOutlineBell } from 'react-icons/ai';
import { BsBoxArrowRight, BsBoxes, BsFillPersonLinesFill, BsGrid3X3Gap } from 'react-icons/bs';
import { CiBoxList, CiCircleInfo, CiFacebook, CiGrid2V, CiGrid32, CiInboxIn, CiInstagram, CiShop, CiViewTimeline } from 'react-icons/ci';
import { FaCrown, FaFacebook, FaFacebookMessenger, FaInfoCircle, FaInstagramSquare, FaWhatsapp } from 'react-icons/fa';
import { FaBoxArchive } from 'react-icons/fa6';
import { FiGrid } from 'react-icons/fi';
import { GiJewelCrown } from 'react-icons/gi';
import { IoIosCheckmarkCircleOutline, IoIosCloseCircleOutline, IoMdCheckmarkCircleOutline } from 'react-icons/io';
import { IoAirplaneOutline, IoBarChartOutline, IoCalendarOutline, IoLogoDropbox, IoLogoWhatsapp } from 'react-icons/io5';
import { LuCrown } from 'react-icons/lu';
import { MdMarkEmailUnread, MdOutlineEmail } from 'react-icons/md';
import { SiSendgrid } from 'react-icons/si';
import { TfiLayoutGrid4Alt } from 'react-icons/tfi';

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string }>;

export const iconMap: Record<string, IconComponent> = {
  ShieldCheck,
  FolderKanban,
  FileSignature,
  User,
  Users,
  FileText,
  Settings,
  Info,
  Wrench,
  Phone,
  HelpCircle,
  Menu,
  Lock,
  ScrollText,
  FileBadge,
  Eye,
  Edit2,
  Trash2,
  Plus,
  GripVertical,
  Save,
  ChevronDown,
  ChevronRight,
  Home,
  Search,
  Bell,
  Mail,
  Calendar,
  Clock,
  Download,
  Upload,
  Copy,
  Check,
  X,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Filter,
  RefreshCw,
  ExternalLink,
  Link,
  Unlink,
  Image: ImageIcon,
  Video,
  Music,
  Camera,
  Mic,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Package,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Folder,
  FolderOpen,
  File,
  FilePlus,
  FileX,
  Bookmark,
  BookmarkPlus,
  Star,
  Heart,
  Share2,
  MessageSquare,
  MessageCircle,
  Send,
  Paperclip,
  Tag,
  Hash,
  AtSign,
  Globe,
  MapPin,
  Navigation,
  Target,
  Award,
  Zap,
  Sun,
  Moon,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Power,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserCheck,
  CiShop,
  CiFacebook,
  FaFacebook,
  FaWhatsapp,
  IoLogoWhatsapp,
  CiInstagram,
  FaInstagramSquare,
  FaFacebookMessenger,
  MdOutlineEmail,
  MdMarkEmailUnread,
  FaCrown,
  LuCrown,
  GiJewelCrown,
  FaInfoCircle,
  CiCircleInfo,
  CiBoxList,
  CiInboxIn,
  IoLogoDropbox,
  FaBoxArchive,
  BsBoxArrowRight,
  BsBoxes,
  CiGrid32,
  CiGrid2V,
  FiGrid,
  BsGrid3X3Gap,
  SiSendgrid,
  TfiLayoutGrid4Alt,
  IoMdCheckmarkCircleOutline,
  IoAirplaneOutline,
  IoBarChartOutline,
  IoCalendarOutline,
  CiViewTimeline,
  IoIosCheckmarkCircleOutline,
  IoIosCloseCircleOutline,
  AiOutlineBell,
  BsFillPersonLinesFill,
};

export const iconOptions = Object.keys(iconMap);
